import { Inter } from "next/font/google";
import "./globals.css";
import SessionProviderComponent from './components/SessionProviderComponent'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Video Upload Streaming Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionProviderComponent>
        <body className={inter.className}>{children}</body>
      </SessionProviderComponent>
    </html>
  );
}
